services:
  # Test services
  postgres_test:
    image: pgvector/pgvector:pg16
    ports:
      - '9090:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: serverpod_admin_test
      POSTGRES_PASSWORD: "EAR3hNdj0t3rOf-nO4evNgdy3VHMqb_r"
    volumes:
      - serverpod_admin_test_data:/var/lib/postgresql/data
  redis_test:
    image: redis:6.2.6
    ports:
      - '9091:6379'
    command: redis-server --requirepass "B0TdapHwtlTnJmR2_1DHDG7r_H3l_di_"
    environment:
      - REDIS_REPLICATION_MODE=master

volumes:
  serverpod_admin_test_data:
