name: serverpod_admin_client
description: The missing admin dashboard for Serverpod. A complete Flutter package providing CRUD operations, foreign key relationships, boolean fields, date pickers, pagination, search, and authentication for managing your Serverpod database records.
version: 1.0.5
# homepage: https://www.example.com
homepage: https://github.com/AdamMusa/serverpod_admin

environment:
  sdk: '>=3.5.0 <4.0.0'
dependencies:
  serverpod_client: 3.0.1
  